import { readFileSync, writeFileSync } from 'node:fs';
const root = new URL('../', import.meta.url);
const css = readFileSync(new URL('style.css', root), 'utf8');
const js = ['parser.js', 'panel.js'].map(file => readFileSync(new URL(file, root), 'utf8').replace(/^export /gm, '')).join('\n');
writeFileSync(new URL('preview.html', root), `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>花笺 · 思考面板预览</title>
<style>${css}
*{box-sizing:border-box}body{margin:0;background:#faf7f8;color:#533f47;font:15px/1.8 system-ui,"Microsoft YaHei",sans-serif}.page{max-width:640px;margin:auto;padding:36px 22px}header{display:flex;align-items:center;justify-content:space-between;margin-bottom:36px}.brand{font-size:21px;font-weight:650;letter-spacing:.1em}.badge{font-size:11px;color:#997982;border:1px solid #eddde3;border-radius:20px;padding:3px 10px}.intro{color:#a18a93;font-size:13px;margin:0 0 35px}.user{margin:0 0 30px auto;width:fit-content;max-width:88%;padding:13px 20px;background:#f1e8ee;border-radius:20px 20px 5px 20px}.name{display:flex;align-items:center;gap:10px;margin:20px 0 12px;font-size:14px}.avatar{width:30px;height:30px;display:grid;place-items:center;border-radius:50%;background:#eec4d3;color:#fff}.mes_text{min-height:70px;padding:3px 4px;line-height:1.9}.controls{display:flex;gap:10px;flex-wrap:wrap;margin-top:36px;border-top:1px solid #ecdee3;padding-top:22px}.controls button{font:inherit;border:1px solid #e8cbd6;border-radius:20px;background:#fff8fb;color:#805866;padding:7px 16px;cursor:pointer}.controls label{display:flex;align-items:center;gap:8px;font-size:13px;color:#947783}.controls input{width:32px;height:32px;border:0;background:transparent}.note{font-size:12px;color:#a18a93;margin-top:18px}.cute-cot{margin-top:0}.mes{display:flex;align-items:flex-start}.mesAvatarWrapper{flex:0 0 40px}.mes_block{min-width:0;flex:1;padding-left:10px;overflow:hidden}.ch_name{height:40px}.mes .avatar{width:40px;height:40px}
</style><main class="page"><header><span class="brand">花笺</span><span class="badge">自定义思考 · 交互预览</span></header><p class="intro">给思绪一点空间，也给正文留一点轻盈。</p><div class="user">帮我写一句轻柔的晚安问候。</div><article class="mes"><div class="mesAvatarWrapper"><span class="avatar">Q</span></div><div class="mes_block"><div class="ch_name">Quirlune</div><div class="mes_text"></div></div></article><div class="controls"><button id="replay">重新播放</button><button id="stop">停止思考</button><label>配色<input id="color" type="color" value="#ed98b4"></label></div><p class="note">思考中自动跟随最新文字；上下滑动可回看，结束后自动收起。<br>此页使用扩展的同一份面板代码，演示文字为模拟数据。</p></main>
<script type="module">${js}
document.querySelector('main').id='chat';document.documentElement.classList.add('cute-cot-smooth-body');document.querySelector('#color').value=DEFAULTS.color;
const node=document.querySelector('.mes'),body=node.querySelector('.mes_text');
let settings={...DEFAULTS},timer,record,started;
const thought='先考虑语气：温柔、自然，不要过度亲昵。\\n把忙碌的一天轻轻放下，留一个可以安静休息的画面。\\n\\n可以选月光、窗边或一阵晚风，但不需要堆叠修饰词。\\n思考区只展示原文。下面这些标记也不会变成样式或组件：\\n<style>body { display: none; }</style>\\n<note>这是一段普通文本</note>\\n**这里也不会变成加粗**\\n\\n最后用一句简短的祝愿收尾，保持自然的节奏。\\n让烦恼先暂停，明天的事情交给明天。';
function showBody(){const reply='愿今晚的月光替你把烦恼放轻。好好休息，明天醒来，又是柔软崭新的一天。';let n=0;timer=setInterval(()=>{const span=document.createElement('span');span.className='text_segment';span.textContent=reply.slice(n,n+4);body.append(span);n+=4;if(n>=reply.length)clearInterval(timer);},90);}
function play(){clearInterval(timer);renderPanel(node,null,settings);body.textContent='';started=Date.now();let i=0;record={status:'thinking',text:'',duration:null};renderPanel(node,record,settings);timer=setInterval(()=>{i+=5;record.text=thought.slice(0,i);renderPanel(node,record,settings);if(i>=thought.length){clearInterval(timer);record.status='done';record.duration=Date.now()-started;renderPanel(node,record,settings);showBody();}},90);}
document.querySelector('#replay').onclick=play;document.querySelector('#stop').onclick=()=>{clearInterval(timer);if(record.status==='thinking'){record.status='interrupted';record.duration=Date.now()-started;renderPanel(node,record,settings);}};document.querySelector('#color').oninput=e=>{settings.color=e.target.value;renderPanel(node,record,settings);};play();
</script></html>`);
